version: '3.8'
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  openf1-api:
    build: .
    command: uvicorn openf1.services.query_api.app:app --host 0.0.0.0 --port 8000
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    ports:
      - "9876:8000"
    depends_on:
      - mongo

volumes:
  mongo_data:
